force-app/main/default/objects/BatalhaDoContato__c/BatalhaDoContato__c.object-meta.xml
<CustomObject>
    <description>Campo responsável por criar a ligação do contato com a batalha</description>
    <label>Batalha do Contato</label>
    <nameField>
        <displayFormat>BATCONTA{0000000}</displayFormat>
        <label>Batalha do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhaDoContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contato que participou da batalha</description>
    <inlineHelpText>Contato que participou da batalha</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas do Contato</relationshipLabel>
    <relationshipName>Contato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de guerra adotado pelo herói</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de guerra adotado pelo herói</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenar as habilidades dos heróis ou vilões</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos contato e habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Level da habilidade que o contato possui</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NomeHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NomeHabilidade__c</fullName>
    <formula>Habilidade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome da Habilidade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EstudoSOQL.cls
public class EstudoSOQL {
	public static List<Contact> getAllContacts(){
        List<Contact> contatos = [SELECT Id, Name FROM Contact];
		return contatos;
				 
    }
    
    public static Contact getContactById(Id contactId){       
        
        List<Contact> contatos = [SELECT Id, Name, NomeDeGuerra__c, (SELECT Id, Habilidade__r.Name, Level__c FROM HabilidadesContato__r) FROM Contact WHERE Id = :contactId LIMIT 1];
        if(!contatos.isEmpty()){
            Contact contato = contatos.get(0);
            
            
            return contato;
        }else{
            return null;
        }
        
        
    }
    
    public static Map<String, Decimal> getAvgByContact(){
        AggregateResult[] results = [SELECT Contato__r.NomeDeGuerra__c NomeDeGuerra, AVG(Level__c) mediaLevel 
                                     FROM HabilidadeContato__c 
                                     GROUP BY Contato__r.NomeDeGuerra__c 
                                     HAVING AVG(Level__c) > 0 
                                     ORDER BY AVG(Level__c) DESC];
        
        Map<String, Decimal> mapa = new Map<String, Decimal>();
        
        for(AggregateResult agResult : results){
            String nomeGuerra = (String) agResult.get('NomeDeGuerra');
            Decimal mediaLevel = (Decimal) agResult.get('mediaLevel');
            mapa.put(nomeGuerra, mediaLevel);
        }
           
        return mapa;
    }
    
    
    public static List<HabilidadeContato__c> getHabilidadesPorContatoOrHabilidade(String nomeDeGuerra, String nomeHabilidade){               
        String query = 'SELECT Id, NomeHabilidade__c, Level__c, Contato__r.NomeDeGuerra__c FROM HabilidadeContato__c WHERE ';
        
        if(!String.isEmpty(nomeDeGuerra)){
            query += ' Contato__r.NomeDeGuerra__c = :nomeDeGuerra';
        }else{
            query += ' Habilidade__r.Name = :nomeHabilidade';
        }
        
        List<HabilidadeContato__c> habilidadesDoContato = Database.query(query);      
        return habilidadesDoContato;
    }
    
	//Para estudar, algumas ótimas funções de consulta 
    //SELECT Id, Contato__r.NomeDeGuerra__c, Habilidade__r.Name, Level__c FROM HabilidadeContato__c WHERE Contato__c in ('0035e00000AOIDeAAP', '0035e00000AOZPCAA5') 
    //SELECT Id, Habilidade__c, Habilidade__r.Name, Level__c FROM HabilidadeContato__c WHERE Contato__c = '0035e00000AOIDeAAP' 
    //SELECT Id, (SELECT Id, Habilidade__r.Name FROM HabilidadesContato__r) FROM Contact WHERE Id = '0035e00000AOIDeAAP'    
    //SOSL -> FIND {Clone OR Ler} IN ALL FIELDS RETURNING Contact(FirstName, NomeDeGuerra__c),Habilidade__c(Name) 
}