force-app/main/default/objects/BatalhaDoContato__c/BatalhaDoContato__c.object-meta.xml
<CustomObject>
    <description>Campo responsável por criar a ligação do contato com a batalha</description>
    <label>Batalha do Contato</label>
    <nameField>
        <displayFormat>BATCONTA{0000000}</displayFormat>
        <label>Batalha do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhaDoContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contato que participou da batalha</description>
    <inlineHelpText>Contato que participou da batalha</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas do Contato</relationshipLabel>
    <relationshipName>Contato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de guerra adotado pelo herói</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de guerra adotado pelo herói</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusDoCandidato__c.field-meta.xml
<CustomField>
    <fullName>StatusDoCandidato__c</fullName>
    <label>Status do Candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aguardando aprovação p/ Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
            </value>
            <value>
                <fullName>Aprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Reprovado na analise do Gestor</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenar as habilidades dos heróis ou vilões</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos contato e habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Level da habilidade que o contato possui</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NomeHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NomeHabilidade__c</fullName>
    <formula>Habilidade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome da Habilidade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Ranking das habilidade</description>
    <inlineHelpText>Apresenta as ordem das habilidades</inlineHelpText>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AtualizaRankigTriggerTest.cls
@istest
public class AtualizaRankigTriggerTest {	    
    @testSetup
     public static void setup(){    
         
         Contact Hulk = new Contact(LastName ='Test hulk'  ,NomeDeGuerra__c='Test hulk', StatusDoCandidato__c = 'Em Treinamento');
         Contact Capita = new Contact(LastName ='Test capitã 2 ',NomeDeGuerra__c='Test capitã 2', StatusDoCandidato__c = 'Em Treinamento');  
         List <Contact> contatos = new List<Contact>();
         contatos.add(Hulk);
         contatos.add(Capita);
         insert contatos;         
         Habilidade__c forte = new Habilidade__c(Name ='Forte');
         Habilidade__c verde = new Habilidade__c(Name ='verde');
         List <Habilidade__c> habilidade = new List<Habilidade__c>(); 
         habilidade.add(forte);
         habilidade.add(verde);
         insert habilidade;                      
         HabilidadeContato__c hab1 = new HabilidadeContato__c();
         hab1.Contato__c = Hulk.Id;
         hab1.Habilidade__c = forte.Id;
         hab1.Level__c = 80; 
         HabilidadeContato__c hab2 = new HabilidadeContato__c();
         hab2.Contato__c = Capita.Id;
         hab2.Habilidade__c = forte.Id;
         hab2.Level__c = 100; 
         HabilidadeContato__c hab3 = new HabilidadeContato__c();
         hab3.Contato__c = Hulk.Id;
         hab3.Habilidade__c = verde.Id;
         List<HabilidadeContato__c> habilidades = new List<HabilidadeContato__c>();
         habilidades.add(hab1);
         habilidades.add(hab2);
         habilidades.add(hab3); 
         insert habilidades;     	
     }
    @isTest 
    public static void TesteInserir() {  
        
        List<HabilidadeContato__c> habilidadesContato = [SELECT Id, NomeHabilidade__c, Ranking__c, Contato__r.NomeDeGuerra__c 
                                                         FROM  HabilidadeContato__c                                                          
                                                         WHERE Ranking__c != null];        
        for (HabilidadeContato__c habilidade : habilidadesContato){
        	system.assertEquals(1, habilidade.Ranking__c);    
        }
        system.assertEquals(2, habilidadesContato.size());                
    }
    
    
    @isTest
    public static void TesteUpdate() {  
        
        List<HabilidadeContato__c> habilidadesContato = [SELECT Id, NomeHabilidade__c, Ranking__c, Contato__r.NomeDeGuerra__c 
                                                         FROM  HabilidadeContato__c];
        
        List<Contact> hulk = [SELECT Id FROM Contact where NomeDeGuerra__c = 'Test hulk' LIMIT 1];
        for (HabilidadeContato__c habilidade : habilidadesContato){             
            if (habilidade.Contato__c == hulk[0].Id && habilidade.NomeHabilidade__c == 'verde'){                
                habilidade.Level__c = 100;
            }                
        }
        
        update habilidadesContato;
        
        List<HabilidadeContato__c> NewhabilidadesContato = [SELECT Id, NomeHabilidade__c, Ranking__c, Contato__r.NomeDeGuerra__c 
                                                         FROM  HabilidadeContato__c];
        system.assertEquals(3, habilidadesContato.size());
        for (HabilidadeContato__c habilidade : NewhabilidadesContato){
            if (habilidade.Contato__r.NomeDeGuerra__c == 'Test hulk' && habilidade.NomeHabilidade__c == 'verde'){
                system.assertEquals(1, habilidade.Ranking__c);
            }                
        }
    }
    
    @isTest
    public static void TesteDelete() {  
        
        List<HabilidadeContato__c> habilidadesContato = [SELECT Id, NomeHabilidade__c, Ranking__c, Contato__r.NomeDeGuerra__c                                                          FROM  HabilidadeContato__c];
        List<Contact> hulk = [SELECT Id FROM Contact where NomeDeGuerra__c = 'Test hulk' LIMIT 1];
        
        List<HabilidadeContato__c> habilidadesdel = new List<HabilidadeContato__c>();
        
        for (HabilidadeContato__c habilidade : habilidadesContato){                          
            if (habilidade.Contato__c == hulk[0].Id && habilidade.NomeHabilidade__c == 'verde'){                 
            	habilidadesdel.add(habilidade);               
            }                      
        }
        
        delete habilidadesdel;
               
        List<HabilidadeContato__c> NewhabilidadesContato = [SELECT Id, NomeHabilidade__c, Ranking__c, Contato__r.NomeDeGuerra__c 
                                                         FROM  HabilidadeContato__c];                
         for (HabilidadeContato__c Newhabilidade : NewhabilidadesContato){             
            if (Newhabilidade.Contato__r.NomeDeGuerra__c == 'Test hulk'){
                System.debug('Newhabilidade'+Newhabilidade);
                system.assertEquals(1, Newhabilidade.Ranking__c);
            }                
        }
    }
}