force-app/main/default/objects/BatalhaDoContato__c/BatalhaDoContato__c.object-meta.xml
<CustomObject>
    <description>Campo responsável por criar a ligação do contato com a batalha</description>
    <label>Batalha do Contato</label>
    <nameField>
        <displayFormat>BATCONTA{0000000}</displayFormat>
        <label>Batalha do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhaDoContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contato que participou da batalha</description>
    <inlineHelpText>Contato que participou da batalha</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas do Contato</relationshipLabel>
    <relationshipName>Contato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NivelDoHeroi__c.field-meta.xml
<CustomField>
    <fullName>NivelDoHeroi__c</fullName>
    <description>Nível de Senioridade do Herói</description>
    <inlineHelpText>Nível de Senioridade do Herói</inlineHelpText>
    <label>Nível do Herói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspira</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de guerra adotado pelo herói</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de guerra adotado pelo herói</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Heroi.recordType-meta.xml
<RecordType>
    <fullName>Heroi</fullName>
    <active>true</active>
    <label>Herói</label>
</RecordType>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos contato e habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Level da habilidade que o contato possui</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetAvailableHeroesIs.cls
/* Listar todos os herois que não estão alocados em batalhas e 
 * ter opção de buscar todos/por habilidade/ por nível do heroi
 */
@RestResource(urlMapping='/marvel/availableHeroes/*')
global class GetAvailableHeroesIs {
	
    @HttpGet
    global static AvailableHeroes doGet(){     
        
        Map<String,Hero> mapHerois = new Map<String,Hero>();
        List<HabilidadeContato__c> lstHabContatos = new  List<HabilidadeContato__c>();
        String habilidadeParam = RestContext.request.params.get('Habilidade');
        
        String nivelParam = RestContext.request.params.get('Nivel');
        
        String dynamicQuery = 'SELECT Id, Contato__r.NomeDeGuerra__c, Habilidade__r.Name, Contato__r.NivelDoHeroi__c, Level__c FROM HabilidadeContato__c where Contato__r.RecordType.DeveloperName = \'Heroi\' and Contato__c NOT IN (SELECT Contato__c  FROM BatalhaDoContato__c)';                   	               
        
        if (!String.isBlank(habilidadeParam)){
            List<String> HabilidadesParam = habilidadeParam.split(',');
            dynamicQuery += ' and Habilidade__r.Name IN :HabilidadesParam';
        }
        if (!String.isBlank(nivelParam)){
            List<String> niveisParam = nivelParam.split(',');
            dynamicQuery += ' and Contato__r.NivelDoHeroi__c IN :niveisParam';
        }
       	
        lstHabContatos = Database.query(dynamicQuery);
                
        for (HabilidadeContato__c habilidadeContato: lstHabContatos){
            
            Skill habilidade = new Skill(habilidadeContato.Habilidade__r.Name,String.valueOf(habilidadeContato.Level__c));
            
            Hero heroi;
            
            if (mapHerois.containsKey(habilidadeContato.Contato__r.NomeDeGuerra__c)){
                heroi = mapHerois.get(habilidadeContato.Contato__r.NomeDeGuerra__c);
                heroi.habilidades.add(habilidade);
            }else{
                heroi = new Hero();
                heroi.nome  = habilidadeContato.Contato__r.NomeDeGuerra__c;
                heroi.nivel  = habilidadeContato.Contato__r.NivelDoHeroi__c;
                heroi.habilidades = new List<Skill>{habilidade};                
            }
            mapHerois.put(habilidadeContato.Contato__r.NomeDeGuerra__c, heroi);
        }		
        //return 'Funcionou';
        //return String.valueOf(lstHabContatos);        
        return new AvailableHeroes(mapHerois.values());
    }        
    global class AvailableHeroes{
        
        public List<Hero> Herois;
        public Integer total;
        
        AvailableHeroes(List<Hero> herois){
            this.Herois = herois;
            this.total = herois.size();
            
        }
    }
    
    global class Hero{
        
        public String nome;
        public String nivel;
        public List<Skill> habilidades;
        
    }
    global class Skill{
        
        public String nome;
        public String nivel;
        
        Skill(String nome, String nivel){
            this.nome = nome;
            this.nivel = nivel;
        }
        
    }    
}