force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos contato e habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Level da habilidade que o contato possui</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EditHabilidadeContatoControllerExtension.cls
public with sharing class EditHabilidadeContatoControllerExtension {
    private Contact contato;
    public List<HabilidadeContato__c> habilidades {get; private set;}
    public EditHabilidadeContatoControllerExtension(ApexPages.StandardController controller) {
        this.contato =(Contact) controller.getRecord();
        this.habilidades = [SELECT id, habilidade__r.Name, Level__c from HabilidadeContato__c where Contato__c = :this.contato.Id ];
    }

    public PageReference cancelar(){
        PageReference pg = new PageReference('/'+this.contato.Id);
        pg.setRedirect(true);
        return pg;
    }
    public void salvar(){
       try{
        update this.contato;
        update this.habilidades;
        ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM,'Os registros foram atualizados'));
       }catch(Exception e){

           System.debug('Erro >>> '+ e.getMessage());
           ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM,'Não foi possível salvar, verifique com o suporte'));
       }
    }
}