force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos contato e habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Level da habilidade que o contato possui</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Ranking das habilidade</description>
    <inlineHelpText>Apresenta as ordem das habilidades</inlineHelpText>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HabilidadeContatoBO.cls
public class HabilidadeContatoBO {
    

    private static final HabilidadeContatoBO instance = new HabilidadeContatoBO();

    private HabilidadeContatoBO(){

    }
    
    public static HabilidadeContatoBO getInstance(){
        return instance; 
    }

    public void AtualizaRanking(Set<Id> idContatosDaHabilidade){
  
            Map<Id,Contact> mapContatosDaHabilidade = new Map<Id,Contact>([SELECT Id, 
                                                                             		(SELECT Id, Name, Level__c 
                                                                              		 FROM HabilidadesContato__r 
                                                                                     WHERE Level__c != null 
                                                                                     ORDER BY Level__c DESC) 
                                                                             FROM Contact 
                                                                             WHERE Id in : idContatosDaHabilidade]);
            
            List<HabilidadeContato__c> newRankinHabilidadeContato = new List<HabilidadeContato__c>();
            for(Contact contato : mapContatosDaHabilidade.values())
            {
                if(!contato.HabilidadesContato__r.isEmpty())
                {
                    Integer posicao = 1;
                    for(HabilidadeContato__c habilidadeContato : contato.HabilidadesContato__r)
                    {
                        habilidadeContato.Ranking__c = posicao++;
                        newRankinHabilidadeContato.add(habilidadeContato);
                    }
                }
            }                        
            update newRankinHabilidadeContato;        
    }
}