force-app/main/default/objects/Contact/fields/DataDaAprovacao__c.field-meta.xml
<CustomField>
    <fullName>DataDaAprovacao__c</fullName>
    <description>Data de aprovação do treinamento</description>
    <inlineHelpText>Data de aprovação do treinamento</inlineHelpText>
    <label>Data da Aprovação</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FeedbackTreinamento__c.field-meta.xml
<CustomField>
    <fullName>FeedbackTreinamento__c</fullName>
    <description>Campo para armazenar informações relevantes do treinamento do usuário</description>
    <inlineHelpText>Campo para armazenar informações relevantes do treinamento do usuário</inlineHelpText>
    <label>Feedback Treinamento</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de guerra adotado pelo herói</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de guerra adotado pelo herói</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ResponsavelAprovacao__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelAprovacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuário responsável por realizar o processo de aprovação do candidato</description>
    <inlineHelpText>Usuário responsável por realizar o processo de aprovação do candidato</inlineHelpText>
    <label>Responsável pela Aprovação</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResponTreinamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusDoCandidato__c.field-meta.xml
<CustomField>
    <fullName>StatusDoCandidato__c</fullName>
    <label>Status do Candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aguardando aprovação p/ Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
            </value>
            <value>
                <fullName>Aprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Reprovado na analise do Gestor</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CriaDocumentoTrienamentoController.cls
public with sharing class CriaDocumentoTrienamentoController {
    
    public Contact contato {get;set;}    
    public CriaDocumentoTrienamentoController() {		

        Id contatoId = ApexPages.currentPage().getParameters().get('Id');
        this.contato = [SELECT Id, Firstname, NomeDeGuerra__c,FeedbackTreinamento__c, ResponsavelAprovacao__c, StatusDoCandidato__c, DataDaAprovacao__c, 
        (SELECT Habilidade__r.Name, Level__c from HabilidadesContato__r ORDER BY Level__c DESC) 
        FROM Contact WHERE Id = :contatoId];
    }
         
}