force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de guerra adotado pelo herói</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de guerra adotado pelo herói</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusDoCandidato__c.field-meta.xml
<CustomField>
    <fullName>StatusDoCandidato__c</fullName>
    <label>Status do Candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aguardando aprovação p/ Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
            </value>
            <value>
                <fullName>Aprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Reprovado na analise do Gestor</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerTeste.cls
@isTest
public class ContactTriggerTeste {
	
    @testSetup
    public static void setup(){
        Contact Thanos = new Contact(LastName ='Test Thanos',RecordTypeId='0125e000000MsVAAA0' ,NomeDeGuerra__c='Test thanos', StatusDoCandidato__c = 'Em Análise');		
        insert Thanos;
    }
        
    @isTest
    public static void verificaTask(){
        List<Contact> contato = [Select Id FROM Contact WHERE LastName ='Test Thanos'];                        
		List<Task> tarefas = [Select Id FROM Task WHERE Subject = 'Descobri fraqueza do vilão' AND Status ='Open' ];           
        System.assertEquals(1,tarefas.size());        
        System.debug('contato depois '+contato);
        delete contato;         
        contato = [Select Id FROM Contact WHERE LastName ='Test Thanos'];  
        System.debug('contato depois '+contato);
        System.assertEquals(1,contato.size());
    }          
}