force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de guerra adotado pelo herói</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de guerra adotado pelo herói</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusDoCandidato__c.field-meta.xml
<CustomField>
    <fullName>StatusDoCandidato__c</fullName>
    <label>Status do Candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aguardando aprovação p/ Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
            </value>
            <value>
                <fullName>Aprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Reprovado na analise do Gestor</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenar as habilidades dos heróis ou vilões</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos contato e habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactCreatTaskTeste.cls
@istest
public class ContactCreatTaskTeste {
  
    @testSetup
    public static void setup(){    
     	Contact Hulk = new Contact(LastName ='Test hulk'  ,NomeDeGuerra__c='Test hulk', StatusDoCandidato__c = 'Em Análise');
        Contact Capita = new Contact(LastName ='Test capitã 2 ',NomeDeGuerra__c='Test capitã 2', StatusDoCandidato__c = 'Em Análise');  
       	List <Contact> contatos = new List<Contact>();
        contatos.add(Hulk);
        contatos.add(Capita);
        insert contatos;
        System.debug('contatos>>'+contatos);
        Habilidade__c forte = new Habilidade__c(Name ='Forte');
        Habilidade__c verde = new Habilidade__c(Name ='verde');
        List <Habilidade__c> habilidade = new List<Habilidade__c>(); 
        habilidade.add(forte);
        habilidade.add(verde);
        insert habilidade;
        System.debug('habilidade>>'+habilidade);
        
        
        HabilidadeContato__c hab1 = new HabilidadeContato__c();
        hab1.Contato__c = Hulk.Id;
        hab1.Habilidade__c = forte.Id;        
        HabilidadeContato__c hab2 = new HabilidadeContato__c();
        hab2.Contato__c = Hulk.Id;
        hab2.Habilidade__c = verde.Id;
        HabilidadeContato__c hab3 = new HabilidadeContato__c();
        hab3.Contato__c = Capita.Id;
        hab3.Habilidade__c = forte.Id;
        
        List<HabilidadeContato__c> habilidades = new List<HabilidadeContato__c>();
        habilidades.add(hab1);
        habilidades.add(hab2);
        habilidades.add(hab3);        
        insert habilidades;   
        System.debug('habilidades>>'+habilidades);
    }
	
    @isTest 
    public static void TestNewTaskForContact() {  
       
        List<Contact> contatos = [SELECT Id FROM Contact WHERE StatusDoCandidato__c = 'Em Análise'];
        
        for(Contact contato : contatos){
            contato.StatusDoCandidato__c = 'Aprovado direto';
        }
        
        update contatos;
        
        List <Task> tarefas = [SELECT Id,Subject,Description from Task]; 
        
        system.assertEquals(2, tarefas.size());
        system.assertEquals('Alocar contato em batalha', tarefas[0].Subject);
           

   		System.debug('Tarefas >>'+ tarefas);       	
    }
}